title: Project

tabs:
  content:
    label: Content
    preset: page
    pages: false
    fields:
      theme:
        label: Thema
        type: text
      projectcover:
        width: 1/3
        extends: sections/image
        label: Cover / Thumbnail
        min: 0
        max: 1
        image:
          ratio: 1/1
          cover: true

      intro:
        width: 2/3
        label: Teaser
        type: textarea
        size: medium

      videoslots:
        label: Aktionen / Inhalte
        type: structure
        columns:
          title:
            width: 1/3
          description:
            width: 1/2
          format:
            width: 1/5

        fields:
          title:
            label: Veranstaltung
            type: text
          format:
            label: Format
            type: select
            options:
              video: Video
              photo: Foto
              statement: Statement
          description:
            label: Beschreibung
            type: textarea
            size: small
          link:
            label: Link
            type: url
          photo:
            label: Fotos
            type: files

  meta:
    label: Meta
    fields:
      datestart:
        width: 1/4
        label: Projektbeginn
        type: date
      dateend:
        width: 1/4
        label: Projektende
        type: date
      timestart:
        width: 1/4
        label: Beginn
        type: time
      timeend:
        width: 1/4
        label: Schluss
        type: time
      groupphoto:
        width: 1/4
        extends: sections/image
        label: Gruppenbild
        min: 0
        max: 1
        image:
          cover: true
      participants:
        width: 1/2
        label: Teilnehmende
        type: multiselect
        options:
          type: query
          query: site.children.template("team").children
      description:
        label: Beschreibung (Antrag)
        width: 1/2
        type: textarea
        size: small
