title: Project

tabs:
  content:
    label: Content
    preset: page
    pages: false
    fields:
      intro:
        label: Intro
        type: textarea
        size: medium

      videoslots:
        label: Videos
        type: structure
        columns:
          date:
            width: 1/6
          title:
            width: 1/6
          format:
            width: 1/6
          description:
            width: 1/3
          link:
            width: 1/6

        fields:
          date:
            label: Datum
            type: date
            default: now
          title:
            label: Veranstaltung
            type: text
          format:
            label: Format
            type: select
            options:
              interview: Interview
              beitrag: Beitrag
              ausflug: Ausflug
          description:
            label: Beschreibung
            type: textarea
            size: small
          link:
            label: Link
            type: url

  makingof:
    label: Making-Of
    preset: page
    pages: false
    fields:
      process:
        label: Prozess
        type: textarea
        size: medium

  meta:
    label: Meta
    fields:
      datestart:
        width: 1/4
        label: Projektbeginn
        type: date
      dateend:
        width: 1/4
        label: Projektende
        type: date
      timestart:
        width: 1/4
        label: Beginn
        type: time
      timeend:
        width: 1/4
        label: Schluss
        type: time
      info:
        label: Beschreibung (Antrag?)
        type: textarea
        size: small
      image:
        width: 1/2
        extends: sections/image
        label: Gruppenbild
        min: 0
        max: 1
        image:
          ratio: 1/1
          cover: true
      participants:
        width: 1/2
        label: Teilnehmende
        type: multiselect
        options:
          type: query
          query: site.children.template("team").children
